[package]
name = "smart_contracts_solana"
version = "0.1.0"
edition = "2024"

[dependencies]
borsh = "1.5.7"
solana-program = "2.3.0"
solana-system-interface = "1.0.0"
spl-token = "8.0.0"
thiserror = "2.0.12"
